# Generated by Django 3.1.1 on 2020-09-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_autor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor_name',
            new_name='author_name',
        ),
    ]
