# Generated by Django 3.1.1 on 2020-09-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200918_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reader',
            new_name='readers',
        ),
    ]
